/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2015 Kurento (http://kurento.org/)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

var inherits = require('inherits');

var kurentoClient = require('kurento-client');

var disguise = kurentoClient.disguise;

var checkType      = kurentoClient.checkType;
var ChecktypeError = checkType.ChecktypeError;


var Transaction = kurentoClient.TransactionsManager.Transaction;

var OpenCVFilter = kurentoClient.register.abstracts.OpenCVFilter;


function noop(error, result) {
  if (error) console.trace(error);

  return result
};


/**
 * Create an element
 *
 * @classdesc
 *  PyEncoder interface. Documentation about the module
 *
 * @extends module:filters/abstracts.OpenCVFilter
 *
 * @constructor module:pyencoder.PyEncoder
 */
function PyEncoder(){
  PyEncoder.super_.call(this);
};
inherits(PyEncoder, OpenCVFilter);


//
// Public methods
//

/**
 * Configures whether filter enabled or not. 0 - disabled, 1 - enabled.
 *
 * @alias module:pyencoder.PyEncoder.setEnabled
 *
 * @param {external:Integer} enabled
 *  Flag filter enabled or not.
 *
 * @param {module:pyencoder.PyEncoder~setEnabledCallback} [callback]
 *
 * @return {external:Promise}
 */
PyEncoder.prototype.setEnabled = function(enabled, callback){
  var transaction = (arguments[0] instanceof Transaction)
                  ? Array.prototype.shift.apply(arguments)
                  : undefined;

  //  
  // checkType('int', 'enabled', enabled, {required: true});
  //  

  var params = {
    enabled: enabled
  };

  callback = (callback || noop).bind(this)

  return disguise(this._invoke(transaction, 'setEnabled', params, callback), this)
};
/**
 * @callback module:pyencoder.PyEncoder~setEnabledCallback
 * @param {external:Error} error
 */

/**
 * Sets session id
 *
 * @alias module:pyencoder.PyEncoder.setSessionId
 *
 * @param {external:String} sessionid
 *  Session id
 *
 * @param {module:pyencoder.PyEncoder~setSessionIdCallback} [callback]
 *
 * @return {external:Promise}
 */
PyEncoder.prototype.setSessionId = function(sessionid, callback){
  var transaction = (arguments[0] instanceof Transaction)
                  ? Array.prototype.shift.apply(arguments)
                  : undefined;

  //  
  // checkType('String', 'sessionid', sessionid, {required: true});
  //  

  var params = {
    sessionid: sessionid
  };

  callback = (callback || noop).bind(this)

  return disguise(this._invoke(transaction, 'setSessionId', params, callback), this)
};
/**
 * @callback module:pyencoder.PyEncoder~setSessionIdCallback
 * @param {external:Error} error
 */


/**
 * @alias module:pyencoder.PyEncoder.constructorParams
 *
 * @property {module:core.MediaPipeline} mediaPipeline
 *  the parent {@link module:core.MediaPipeline MediaPipeline}
 */
PyEncoder.constructorParams = {
  mediaPipeline: {
    type: 'kurento.MediaPipeline',
    required: true
  }
};

/**
 * @alias module:pyencoder.PyEncoder.events
 *
 * @extends module:filters/abstracts.OpenCVFilter.events
 */
PyEncoder.events = OpenCVFilter.events;


/**
 * Checker for {@link module:pyencoder.PyEncoder}
 *
 * @memberof module:pyencoder
 *
 * @param {external:String} key
 * @param {module:pyencoder.PyEncoder} value
 */
function checkPyEncoder(key, value)
{
  if(!(value instanceof PyEncoder))
    throw ChecktypeError(key, PyEncoder, value);
};


module.exports = PyEncoder;

PyEncoder.check = checkPyEncoder;
